version: '3'

tasks:
  test:
    desc: Run all backend tests
    cmds:
      - pytest backend/tests

  dev:
    desc: Run the development server
    cmds:
      - uvicorn backend.app.main:app --reload
