version: '3'

tasks:
  install:
    desc: Install dependencies
    cmds:
      - pip install -r backend/requirements.txt

  test:
    desc: Run all backend tests
    cmds:
      - cd backend && PYTHONPATH=. pytest tests/test_csv_service.py
    preconditions:
      - task: install

  dev:
    desc: Run the application in development mode
    cmds:
      - uvicorn app.main:app --reload
