import { ExportFormat } from "../components/modals/ExportPackageModal";

export function assembleAppProps(p: any) {
  const reviewImportProps = {
    onNavigateHome: () => p.navigate("/"),
    onNavigateResponses: () => p.navigate("/responses"),
    formUrl: p.ingestion.formUrl,
    setFormUrl: p.ingestion.setFormUrl,
    loadFormUrl: p.ingestion.loadFormUrl,
    loadFormFile: p.ingestion.loadFormFile,
    sourceStatus: p.notice,
    detectedQuestions: p.workflow.detectedQuestions,
    parsedQuestions: p.ingestion.parsedQuestions,
    uploadedFile: p.ingestion.uploadedFormFile,
    uploadedFileContent: p.ingestion.uploadedFileContent,
    onUpdateQuestions: (qs: any[]) => {
      p.ingestion.setParsedQuestions(qs);
      p.workflow.setDetectedQuestions(qs.filter((q) => q.selected).map((q) => q.question_text));
    },
    onRephraseQuestion: p.ingestion.handleRephraseQuestion,
    onReparseWithGuidance: (guidance: string) =>
      p.ingestion.handleReparseWithGuidance(guidance, p.workflow.setDetectedQuestions),
    onSubmitFeedback: p.ingestion.handleSubmitParserFeedback,
    openWorkspace: () => p.navigate(`/response/workspace/${p.activeResponseId}`),
    onConfirmImport: (curated: any[]) => p.handleConfirmImport(curated),
  };

  const questionnaireProps = {
    onNavigateHome: () => p.navigate("/"),
    onNavigateResponses: () => p.navigate("/responses"),
    onOpenImport: (id: string) => p.navigate(`/review/${id}`),
    responseId: p.activeResponseId,
    sourceMode: p.workflow.sourceMode,
    sourceLabel: p.workflow.sourceLabel,
    openOriginalForm: p.openOriginalForm,
    detectedQuestions: p.workflow.detectedQuestions,
    question: p.workflow.question,
    setQuestion: p.workflow.setQuestion,
    tenantId: p.tenantId,
    setTenantId: p.setTenantId,
    generateAnswer: p.generateAnswer,
    generateAllAnswers: p.generateAllAnswers,
    isGenerating: p.ai.isGenerating,
    role: p.workflow.role,
    setRole: p.workflow.setRole,
    showToast: p.activity.showToast,
    approvedCount: p.workflow.approvedCount,
    inReviewCount: p.workflow.inReviewCount,
    changesRequestedCount: p.workflow.changesRequestedCount,
    isBatchApproved: p.workflow.isBatchApproved,
    handleBatchApproveAll: p.handleBatchApproveAll,
    handleReviewReset: p.workflow.handleReviewReset,
    isAllApproved: p.workflow.isAllApproved,
    exportAnswers: () => p.setShowExportModal(true),
    onOpenExportModal: () => p.setShowExportModal(true),
    reviewStatusByQuestion: p.workflow.reviewStatusByQuestion,
    reviewCommentsByQuestion: p.review.reviewCommentsByQuestion,
    answersByQuestion: p.workflow.answersByQuestion,
    setAnswersByQuestion: p.workflow.setAnswersByQuestion,
    saveAnswers: p.workflow.saveAnswers,
    handleRequestChanges: p.handleRequestChanges,
    openSendForReviewModal: p.openSendForReviewModal,
    handleApproveQuestion: p.handleApproveQuestion,
    handleIndividualReview: p.workflow.handleIndividualReview,
    promotedQuestions: p.workflow.promotedQuestions,
    handlePromoteToKnowledgeBase: p.handlePromoteToKnowledgeBase,
    notice: p.notice,
    answer: p.ai.answer,
    setAnswer: p.ai.setAnswer,
    response: p.ai.response,
    activeSource: p.ai.activeSource,
    setActiveSource: p.ai.setActiveSource,
  };

  const shellProps = {
    mobileNavOpen: p.mobileNavOpen,
    setMobileNavOpen: p.setMobileNavOpen,
    companyName: p.settings.workspaceSettings.company_name,
    onOpenSettings: () => p.settings.setShowSettingsModal(true),
    backendHealth: p.activity.backendHealth,
    isOverviewActive: p.isOverviewActive,
    isResponsesActive: p.isResponsesActive,
    isKbActive: p.isKbActive,
    isPlaygroundActive: p.isPlaygroundActive,
    isActivityActive: p.isActivityActive,
    recentRFPs: p.workspaces.recentRFPs,
    activeResponseId: p.activeResponseId,
    onNavigateHome: () => { p.kb.setShowKBModal(false); p.activity.setShowActivityModal(false); p.navigate("/"); },
    onNavigateResponses: () => { p.kb.setShowKBModal(false); p.activity.setShowActivityModal(false); p.navigate("/responses"); },
    onSelectRFP: (id: string) => { p.kb.setShowKBModal(false); p.activity.setShowActivityModal(false); p.workflow.setResponseId(id); p.navigate(`/response/workspace/${id}`); },
    onOpenKB: (tab: any) => { p.activity.setShowActivityModal(false); p.kb.setKbModalTab(tab); p.kb.setShowKBModal(true); p.navigate(tab === "playground" ? "/playground" : "/knowledge-base"); },
    onOpenActivity: () => { p.kb.setShowKBModal(false); p.activity.setShowActivityModal(true); },
    showSettingsModal: p.settings.showSettingsModal,
    kbTotalRecords: p.kb.kbTotalRecords,
    kbTotalSources: p.kb.kbTotalSources,
    tenantId: p.tenantId,
    toastNotice: p.activity.toastNotice,
  };

  const mainViewProps = {
    route: p.route,
    formUrl: p.ingestion.formUrl,
    setFormUrl: p.ingestion.setFormUrl,
    loadFormUrl: p.ingestion.loadFormUrl,
    loadFormFile: p.ingestion.loadFormFile,
    openImport: (id?: string) => p.navigate(`/review/${id || p.activeResponseId}`),
    isParsingDocument: p.ingestion.isParsingDocument,
    parsingProgress: p.ingestion.parsingProgress,
    workspaceSummaries: p.workspaces.workspaceSummaries,
    isWorkspacesLoading: p.workspaces.isWorkspacesLoading,
    onSelectWorkspace: (id: string) => { p.workflow.setResponseId(id); p.navigate(`/response/workspace/${id}`); },
    handleDuplicateWorkspace: (id: string) => p.workspaces.handleDuplicateWorkspace(id, p.activity.showToast),
    handleDeleteWorkspace: (id: string) => p.workspaces.handleDeleteWorkspace(id, p.activity.showToast),
    handleExportWorkspace: p.handleExportWorkspace,
    onNewQuestionnaire: () => p.navigate("/"),
    fetchWorkspaceSummaries: p.workspaces.fetchWorkspaceSummaries,
    questionnaireProps,
  };

  const modalsProps = {
    showReviewModal: p.review.showReviewModal,
    setShowReviewModal: p.review.setShowReviewModal,
    reviewTargetRole: p.review.reviewTargetRole,
    setReviewTargetRole: p.review.setReviewTargetRole,
    reviewSelectedQuestion: p.review.reviewSelectedQuestion,
    reviewModalScope: p.review.reviewModalScope,
    setReviewModalScope: p.review.setReviewModalScope,
    reviewInstructions: p.review.reviewInstructions,
    setReviewInstructions: p.review.setReviewInstructions,
    submitSendForReview: p.submitSendForReview,
    allQuestionsCount: p.workflow.allCurrentQuestions.length,
    currentQuestionText: p.workflow.question,
    showKBModal: p.kb.showKBModal,
    closeKBModal: () => { p.kb.setShowKBModal(false); if (p.route === "/knowledge-base" || p.route === "/playground") p.navigate(p.workflow.responseId ? `/response/workspace/${p.workflow.responseId}` : "/"); },
    kbModalTab: p.kb.kbModalTab,
    setKbModalTab: (tab: any) => { p.kb.setKbModalTab(tab); p.navigate(tab === "playground" ? "/playground" : "/knowledge-base"); },
    isDragOver: p.kb.isDragOver,
    setIsDragOver: p.kb.setIsDragOver,
    isUploadingKB: p.kb.isUploadingKB,
    handleKBUpload: p.kb.handleKBUpload,
    kbUploadMsg: p.kb.kbUploadMsg,
    isFetchingKB: p.kb.isFetchingKB,
    kbEntries: p.kb.kbEntries,
    fetchKBEntries: p.kb.fetchKBEntries,
    handleDeleteKBEntry: p.kb.handleDeleteKBEntry,
    playgroundTopK: p.kb.playgroundTopK,
    setPlaygroundTopK: p.kb.setPlaygroundTopK,
    playgroundQuery: p.kb.playgroundQuery,
    setPlaygroundQuery: p.kb.setPlaygroundQuery,
    playgroundLoading: p.kb.playgroundLoading,
    handlePlaygroundSearch: p.kb.handlePlaygroundSearch,
    playgroundError: p.kb.playgroundError,
    playgroundResult: p.kb.playgroundResult,
    apiBaseUrl: p.apiBaseUrl,
    tenantId: p.tenantId,
    kbTotalRecords: p.kb.kbTotalRecords,
    kbTotalSources: p.kb.kbTotalSources,
    showActivityModal: p.activity.showActivityModal,
    setShowActivityModal: p.activity.setShowActivityModal,
    activityLogs: p.activity.activityLogs,
    showSettingsModal: p.settings.showSettingsModal,
    setShowSettingsModal: p.settings.setShowSettingsModal,
    workspaceSettings: p.settings.workspaceSettings,
    setWorkspaceSettings: p.settings.setWorkspaceSettings,
    saveWorkspaceSettings: p.settings.saveWorkspaceSettings,
    exportWorkspaceData: () => p.settings.exportWorkspaceData(p.workspaces.recentRFPs, p.kb.kbEntries),
    isSavingSettings: p.settings.isSavingSettings,
    settingsSaveNotice: p.settings.settingsSaveNotice,
    recentRfpsCount: p.workspaces.recentRFPs.length,
    settingsTab: p.settings.settingsTab,
    setSettingsTab: p.settings.setSettingsTab,
    showExportModal: p.showExportModal,
    setShowExportModal: p.setShowExportModal,
    sourceLabel: p.workflow.sourceLabel,
    totalQuestions: p.workflow.detectedQuestions.length > 0 ? p.workflow.detectedQuestions.length : 1,
    approvedCount: p.workflow.approvedCount,
    handleExportPackage: (f: ExportFormat) => p.handleExportPackage(f),
    revisionItem: p.revisionItem,
    setRevisionItem: p.setRevisionItem,
    onSaveRevisionFeedback: p.onSaveRevisionFeedback,
    role: p.workflow.role,
    reviewCommentsByQuestion: p.review.reviewCommentsByQuestion,
  };

  return { reviewImportProps, questionnaireProps, shellProps, mainViewProps, modalsProps };
}
