import React from "react";
import { Sparkles, RefreshCw, BookOpen } from "lucide-react";
import { ExemplarItem } from "../../types";
import { EditorHeading } from "./response-editor/EditorHeading";
import { ExemplarsBanner } from "./response-editor/ExemplarsBanner";
import { EditorActionsBar } from "./response-editor/EditorActionsBar";

interface ResponseEditorPanelProps {
  notice: string;
  answer: string;
  setAnswer: (answer: string) => void;
  generateAnswer: () => void;
  handleRequestChanges: (question: string) => void;
  handleApproveQuestion: (question: string) => void;
  question: string;
  reviewStatusByQuestion: Record<string, string>;
  promotedQuestions: Record<string, boolean>;
  handlePromoteToKnowledgeBase: (question: string, index: number) => void;
  sourcesCount: number;
  exemplarsUsed?: ExemplarItem[];
  toneApplied?: string;
}

export const ResponseEditorPanel: React.FC<ResponseEditorPanelProps> = ({
  notice,
  answer,
  setAnswer,
  generateAnswer,
  handleRequestChanges,
  handleApproveQuestion,
  question,
  reviewStatusByQuestion,
  promotedQuestions,
  handlePromoteToKnowledgeBase,
  sourcesCount,
  exemplarsUsed,
  toneApplied,
}) => {
  const isApproved = reviewStatusByQuestion[question]?.toLowerCase().includes("approve");
  const exemplars = exemplarsUsed || [];

  return (
    <>
      <EditorHeading notice={notice} />
      <div className="answer-panel panel">
        <div className="answer-toolbar">
          <span className="source-label" style={{ display: "inline-flex", alignItems: "center", gap: "6px", fontWeight: 600, color: "var(--blue)" }}>
            <Sparkles size={14} /> ✍️ Proposal Drafter
          </span>
          <button
            className="ghost-button"
            onClick={generateAnswer}
            disabled={isApproved}
            title={isApproved ? "Response is already approved" : "Re-draft response with AI"}
          >
            <RefreshCw size={14} /> Re-draft
          </button>
        </div>

        <ExemplarsBanner exemplars={exemplars} toneApplied={toneApplied} />

        <textarea
          className="answer-editor"
          value={answer}
          onChange={(event) => setAnswer(event.target.value)}
        />

        <EditorActionsBar
          answerLength={answer.length}
          question={question}
          isApproved={Boolean(isApproved)}
          isPromoted={Boolean(promotedQuestions[question])}
          onRequestChanges={handleRequestChanges}
          onApproveQuestion={handleApproveQuestion}
          onPromoteToKB={(q) => handlePromoteToKnowledgeBase(q, 0)}
        />
      </div>
      <div className="review-note">
        <span className="note-icon"><BookOpen size={15} /></span>
        <p>
          <strong>Review before approving.</strong> This draft was generated by your{" "}
          <strong>AI Proposal Drafter</strong> and grounded in {sourcesCount} retrieved sources. Check that the language matches your current policy.
        </p>
      </div>
    </>
  );
};
