import React from "react";
import { Sparkles, RefreshCw, ThumbsDown, Check, BookOpen } from "lucide-react";

interface ResponseEditorPanelProps {
  notice: string;
  answer: string;
  setAnswer: (answer: string) => void;
  generateAnswer: () => void;
  handleRequestChanges: (question: string) => void;
  handleApproveQuestion: (question: string) => void;
  question: string;
  reviewStatusByQuestion: Record<string, string>;
  promotedQuestions: Record<string, boolean>;
  handlePromoteToKnowledgeBase: (question: string, index: number) => void;
  sourcesCount: number;
}

export const ResponseEditorPanel: React.FC<ResponseEditorPanelProps> = ({
  notice,
  answer,
  setAnswer,
  generateAnswer,
  handleRequestChanges,
  handleApproveQuestion,
  question,
  reviewStatusByQuestion,
  promotedQuestions,
  handlePromoteToKnowledgeBase,
  sourcesCount,
}) => {
  const isApproved = reviewStatusByQuestion[question]?.toLowerCase().includes("approve");

  return (
    <>
      <div className="section-heading">
        <div>
          <p className="eyebrow">02 / Draft response</p>
          <h2>Drafted by Proposal Drafter</h2>
        </div>
        <span className="live-badge">
          <span /> {notice.includes("live") ? "Live" : "Preview"}
        </span>
      </div>
      <div className="answer-panel panel">
        <div className="answer-toolbar">
          <span
            className="source-label"
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: "6px",
              fontWeight: 600,
              color: "var(--blue)",
            }}
          >
            <Sparkles size={14} /> ✍️ Proposal Drafter
          </span>
          <button className="ghost-button" onClick={generateAnswer}>
            <RefreshCw size={14} /> Re-draft
          </button>
        </div>
        <textarea
          className="answer-editor"
          value={answer}
          onChange={(event) => setAnswer(event.target.value)}
        />
        <div className="answer-footer">
          <span>{answer.length} characters</span>
          <div className="answer-actions">
            <button
              className="reject-button"
              onClick={() => handleRequestChanges(question)}
            >
              <ThumbsDown size={15} /> Request changes
            </button>
            <button
              className="approve-button"
              onClick={() => handleApproveQuestion(question)}
            >
              <Check size={15} /> Approve answer
            </button>
            {isApproved && (
              promotedQuestions[question] ? (
                <span
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    gap: "4px",
                    fontSize: "12px",
                    fontWeight: 700,
                    color: "#b45309",
                    background: "#fef3c7",
                    padding: "5px 12px",
                    borderRadius: "9999px",
                    border: "1px solid #fcd34d",
                  }}
                >
                  <Sparkles size={13} /> ⭐ Promoted to KB
                </span>
              ) : (
                <button
                  className="primary-button"
                  style={{
                    background: "linear-gradient(135deg, #f59e0b 0%, #d97706 100%)",
                    borderColor: "#b45309",
                    fontSize: "12px",
                    padding: "6px 12px",
                    display: "inline-flex",
                    alignItems: "center",
                    gap: "5px",
                    color: "#ffffff",
                    fontWeight: 700,
                  }}
                  onClick={() => handlePromoteToKnowledgeBase(question, 0)}
                  title="Promote verified answer to canonical Knowledge Base as Golden Q&A"
                >
                  <Sparkles size={14} /> ⭐ Promote to KB
                </button>
              )
            )}
          </div>
        </div>
      </div>
      <div className="review-note">
        <span className="note-icon">
          <BookOpen size={15} />
        </span>
        <p>
          <strong>Review before approving.</strong> This draft was generated by your{" "}
          <strong>AI Proposal Drafter</strong> and grounded in {sourcesCount} retrieved sources. Check that the language matches your current policy.
        </p>
      </div>
    </>
  );
};
